version: '3'
services:
  ros-foxy-desktop-hsr-sim:
    image: hsr_sim:foxy
    environment:
      - DISPLAY=unix${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./ros2_ws:/home/ros2_ws
    devices:
      - "/dev/dri:/dev/dri"
    network_mode: host
    command: tail -f /dev/null